CREATE DATABASE QUANLYBANHANG

CREATE TABLE KHACHHANG
	(
		MAKH CHAR(4) PRIMARY KEY,
		HOTEN VARCHAR(40),
		DCHI VARCHAR(50),
		SODT VARCHAR(20),
		NGSINH SMALLDATETIME,
		NGDK SMALLDATETIME,
		DOANHSO MONEY
	)
CREATE TABLE NHANVIEN
	(
		MANV CHAR(4) PRIMARY KEY,
		HOTEN VARCHAR(40),
		SODT VARCHAR(20),
		NGVL SMALLDATETIME
	)
CREATE TABLE SANPHAM
	(
		MASP CHAR(4) PRIMARY KEY,
		TENSP VARCHAR(40),
		DVT VARCHAR(20),
		NUOCSX VARCHAR(40),
		GIA MONEY
	)
CREATE TABLE HOADON
	(
		SOHD int PRIMARY KEY,
		NGHD SMALLDATETIME,
		MAKH CHAR(4),
		MANV CHAR(4),
		TRIGIA MONEY
		CONSTRAINT FK_MAKHinHOADON FOREIGN KEY (MAKH)
    REFERENCES KHACHHANG(MAKH),
		CONSTRAINT FK_MANVinHOADON FOREIGN KEY (MANV)
	REFERENCES NHANVIEN(MANV)
	)
CREATE TABLE CTHD
	(
		SOHD int NOT NULL,
		MASP CHAR(4) NOT NULL,
		SL int,
		CONSTRAINT FK_SOHDinCTHD FOREIGN KEY (SOHD)
	REFERENCES HOADON(SOHD),
		CONSTRAINT FK_MASPinCTHD FOREIGN KEY (MASP)
	REFERENCES SANPHAM(MASP)
	)
DROP TABLE CTHD 
ALTER TABLE CTHD
ADD PRIMARY KEY (SOHD, MASP)

CREATE DATABASE QUANLYGIAOVU
CREATE TABLE GIAOVIEN 
	(
		MAGV CHAR(4) PRIMARY KEY,
		HOTEN VARCHAR(40),
		HOCVI VARCHAR(10),
		HOCHAM VARCHAR(10),
		GIOITINH VARCHAR(3),
		NGSINH SMALLDATETIME,
		NGVL SMALLDATETIME,
		HESO NUMERIC(4, 2),
		MUCLUONG MONEY,
		MAKHOA VARCHAR(4)
	)

CREATE TABLE KHOA 
	(
		MAKHOA VARCHAR(4) PRIMARY KEY,
		TENKHOA VARCHAR(40),
		NGTLAP SMALLDATETIME,
		TRGKHOA CHAR(4)
		CONSTRAINT FK_TRGKHOAinKHOA FOREIGN KEY (TRGKHOA)
	REFERENCES GIAOVIEN(MAGV)
	)
CREATE TABLE MONHOC 
	(
		MAMH VARCHAR(10) PRIMARY KEY,
		TENMH VARCHAR(40),
		TCLT TINYINT,
		TCTH TINYINT,
		MAKHOA VARCHAR(4),
		CONSTRAINT FK_MAKHOAinMONHOC FOREIGN KEY (MAKHOA)
	REFERENCES KHOA(MAKHOA)
	)
CREATE TABLE DIEUKIEN
	(
		MAMH VARCHAR(10) not null,
		MAMH_TRUOC VARCHAR(10) not null
		CONSTRAINT FK_MAMHinDIEUKIEN FOREIGN KEY (MAMH)
	REFERENCES MONHOC(MAMH),
		CONSTRAINT FK_MAMH_TRUOCinDIEUKIEN FOREIGN KEY (MAMH_TRUOC)
	REFERENCES MONHOC(MAMH)
	)
ALTER TABLE DIEUKIEN
ADD PRIMARY KEY(MAMH, MAMH_TRUOC)

CREATE TABLE HOCVIEN 
	(
		MAHV CHAR(5) PRIMARY KEY,
		HO VARCHAR(40),
		TEN VARCHAR(10),
		NGSINH SMALLDATETIME,
		GIOITINH VARCHAR(3),
		NOISINH VARCHAR(40),
		MALOP CHAR(3)
	)

CREATE TABLE LOP
	(
		MALOP CHAR(3) PRIMARY KEY,
		TENLOP VARCHAR(40),
		TRGLOP CHAR(5),
		SISO TINYINT,
		MAGVCN CHAR(4)
		CONSTRAINT FK_TRGLOPinLOP FOREIGN KEY (TRGLOP)
	REFERENCES HOCVIEN(MAHV)
	)
CREATE TABLE GIANGDAY 
	(
		MALOP CHAR(3) not null,
		MAMH VARCHAR(10) not null,
		MAGV CHAR(4),
		HOCKY TINYINT,
		NAM SMALLINT,
		TUNGAY SMALLDATETIME,
		DENNGAY SMALLDATETIME
		CONSTRAINT FK_MALOPinGIANGDAY FOREIGN KEY (MALOP)
	REFERENCES LOP(MALOP),
		CONSTRAINT FK_MAMHinGIANGDAY FOREIGN KEY (MAMH)
	REFERENCES MONHOC(MAMH),
	)
ALTER TABLE GIANGDAY
ADD PRIMARY KEY(MALOP, MAMH)

CREATE TABLE KETQUATHI
	(
		MAHV CHAR(5) not null,
		MAMH VARCHAR(10) not null,
		LANTHI TINYINT not null,
		NGTHI SMALLDATETIME,
		DIEM NUMERIC(4, 2),
		KQUA VARCHAR(10),
		CONSTRAINT FK_MAHVinKETQUATHI FOREIGN KEY (MAHV)
	REFERENCES HOCVIEN(MAHV),
		CONSTRAINT FK_MAMHinKETQUATHI FOREIGN KEY (MAMH)
	REFERENCES MONHOC(MAMH)
	)
ALTER TABLE KETQUATHI
ADD PRIMARY KEY(MAHV, MAMH, LANTHI)

/*Cau 2 */
--2.2
	ALTER TABLE SANPHAM
	ADD GHICHU VARCHAR(20);

--2.3
	ALTER TABLE KHACHHANG
	ADD LOAIKH TINYINT;

--2.4
	ALTER TABLE SANPHAM
	ALTER COLUMN GHICHU VARCHAR(100);

--2.5
	ALTER TABLE SANPHAM
	DROP COLUMN GHICHU;

--2.6
	ALTER TABLE KHACHHANG
	ALTER COLUMN LOAIKH VARCHAR(100);

--2.7
	ALTER TABLE SANPHAM
	ADD CHECK(DVT = 'çay' OR DVT = 'hop' OR DVT = 'cai' OR DVT = 'quyen' OR DVT = 'chuc');

--2.8 
	ALTER TABLE SANPHAM
	ADD CHECK(GIA >= 500);

--2.9
	ALTER TABLE CTHD
	ADD CHECK(SL >= 1);

--2.10
	ALTER TABLE KHACHHANG
	ADD CHECK(NGDK > NGSINH);

/*Cau 3 */
--3.3
	ALTER TABLE HOCVIEN
	ADD CHECK(GIOITINH = 'Nam' OR GIOITINH = 'Nu');

--3.4
	ALTER TABLE KETQUATHI
	ADD CHECK((DIEM BETWEEN 0 AND 10) AND LEN(SUBSTRING(CAST(DIEM AS varchar), CHARINDEX('.', DIEM) + 1, 1000)) >= 2);
--3.5
	ALTER TABLE KETQUATHI
	ADD CHECK(KQUA = IIF(DIEM >= 5 AND DIEM <= 10, 'Dat', 'Khong dat'));

--3.6
	ALTER TABLE KETQUATHI
	ADD CHECK(LANTHI <= 3);

--3.7
	ALTER TABLE GIANGDAY
	ADD CHECK(HOCKY >=1 AND HOCKY <= 3);

--3.8
	ALTER TABLE GIAOVIEN
	ADD CHECK(HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));